### ISSUE TITLE
SignUp: same email signup

### ISSUE THREAD

**Issue by olgabartnicki** [sparkrnyc/sparkr_mobile#76] opened 2017-12-28 19:11 UTC
Allows to sign up with the same email address mutliple times. Instead it should notice that this email address has signed up already.

**Comment by remkohdev** [comment] 2017-12-28 19:35
Ah! wait, did you use that TestOlga email after the first time? that means possibly that the other failed signups are caused by this duplicate email, it errors and returns without successfully signing up.

**Comment by remkohdev** [comment] 2017-12-28 20:57
Same issue as #74 and #77

**Comment by remkohdev** [comment] 2018-01-05 22:03
Loopback already doesn't allow it, but no error messaging was displaying the correct error and that signup failed with duplicate email. Fixed by adding error messaging.

**Closed as completed by remkohdev** 2018-01-05 22:03 UTC
Labels: duplicate, enhancement, good first issue
